language: c
env:
  #- ARDUINO_VERSION=1.6.13
  - ARDUINO_VERSION=1.8.13
before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16"
  - sleep 3
  - export DISPLAY=:1.0
  - wget http://downloads.arduino.cc/arduino-$ARDUINO_VERSION-linux64.tar.xz
  - tar xf arduino-$ARDUINO_VERSION-linux64.tar.xz
  - sudo mv arduino-$ARDUINO_VERSION /usr/local/share/arduino
  - sudo ln -s /usr/local/share/arduino/arduino /usr/local/bin/arduino
install:
  - ln -s $PWD /usr/local/share/arduino/libraries/libuavesp
  - arduino --pref "boardsmanager.additional.urls=http://arduino.esp8266.com/stable/package_esp8266com_index.json" --install-boards esp8266:esp8266
  - arduino --pref "boardsmanager.additional.urls=" --save-prefs;
  - arduino --pref "boardsmanager.additional.urls=https://dl.espressif.com/dl/package_esp32_index.json" --install-boards esp32:esp32;
  - arduino --pref "boardsmanager.additional.urls=" --save-prefs;
  - arduino --pref "compiler.warning_level=none" --save-prefs
  # - arduino --install-library "DHT sensor library:1.3.0,Adafruit Unified Sensor:1.0.2"
script:
  - arduino --verify --board esp8266:esp8266:generic:xtal=80,eesz=4M1M,FlashMode=qio,FlashFreq=80,dbg=Serial,lvl=CORE $PWD/examples/Order66/Order66.ino
  - arduino --verify --board esp32:esp32:huzzah $PWD/examples/Order66/Order66.ino
  #- arduino --verify --board esp32:esp32:esp32wrover $PWD/examples/Order66/Order66.ino
